### ISSUE TITLE
Mac OS Version ?

### ISSUE THREAD

**Issue by RainbowDash53** [nirewen/discord-netflix#22]
Hi, I've a Mac, how to use it on an Mac?

**Comment by JRoy** [comment]
There is not pre-made installer for Mac, See: https://github.com/nirewen/discord-netflix#running

**Comment by NovusTheory** [comment]
@nirewen couldn't you setup Travis CI on this repo and get an OSX build? This can also be applicable to automating linux and windows builds too (I believe linux in Travis does the Windows build)

**Comment by nirewen** [comment]
@NovusTheory I was looking for a bot to do this. Thanks!

**Comment by haboutnnah** [comment]
Tried it, got this:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/10.11.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dist' ]
2 info using npm@6.4.1
3 info using node@v10.11.0
4 verbose run-script [ 'predist', 'dist', 'postdist' ]
5 info lifecycle Netflix@1.0.6~predist: Netflix@1.0.6
6 info lifecycle Netflix@1.0.6~dist: Netflix@1.0.6
7 verbose lifecycle Netflix@1.0.6~dist: unsafe-perm in lifecycle true
8 verbose lifecycle Netflix@1.0.6~dist: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/Manu/Downloads/discord-netflix-master/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
9 verbose lifecycle Netflix@1.0.6~dist: CWD: /Users/Manu/Downloads/discord-netflix-master
10 silly lifecycle Netflix@1.0.6~dist: Args: [ '-c', 'build' ]
11 silly lifecycle Netflix@1.0.6~dist: Returned: code: 1  signal: null
12 info lifecycle Netflix@1.0.6~dist: Failed to exec dist script
13 verbose stack Error: Netflix@1.0.6 dist: `build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid Netflix@1.0.6
15 verbose cwd /Users/Manu/Downloads/discord-netflix-master
16 verbose Darwin 17.7.0
17 verbose argv "/usr/local/Cellar/node/10.11.0/bin/node" "/usr/local/bin/npm" "run" "dist"
18 verbose node v10.11.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error Netflix@1.0.6 dist: `build`
22 error Exit status 1
23 error Failed at the Netflix@1.0.6 dist script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
