### ISSUE TITLE
Create installer error (npm run dist)

### ISSUE THREAD

**Issue by lollilol** [nirewen/discord-netflix#41]
When i try to compile the app (to make an installer etc) there is an error:
I used windows git bash
Here's my console output:

```
lollilol@DESKTOP-I36RVTN MINGW64 /d/lollilol/Desktop
$ git clone https://github.com/nirewen/discord-netflix.git
Cloning into 'discord-netflix'...
remote: Enumerating objects: 80, done.
remote: Counting objects: 100% (80/80), done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 221 (delta 32), reused 64 (delta 24), pack-reused 141
Receiving objects: 100% (221/221), 151.56 KiB | 689.00 KiB/s, done.
Resolving deltas: 100% (108/108), done.

lollilol@DESKTOP-I36RVTN MINGW64 /d/lollilol/Desktop
$ cd discord-netflix/

lollilol@DESKTOP-I36RVTN MINGW64 /d/lollilol/Desktop/discord-netflix (master)
$ npm install

> electron@3.0.9 postinstall D:\lollilol\Desktop\discord-netflix\node_modules\electron
> node install.js


> electron-widevinecdm@5.0.2 postinstall D:\lollilol\Desktop\discord-netflix\node_modules\electron-widevinecdm
> node install.js

Downloading widevinecdm_darwin_x64.zip...
Downloading widevinecdm_win32_x64.zip...
Downloading widevinecdm_win32_ia32.zip...
Downloading widevinecdm_linux_x64.zip...
widevinecdm_win32_ia32.zip is downloaded & extracted.
widevinecdm_linux_x64.zip is downloaded & extracted.
{ Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:139:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-widevinecdm@5.0.2 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-widevinecdm@5.0.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lollilol\AppData\Roaming\npm-cache\_logs\2018-11-20T15_52_26_032Z-debug.log

lollilol@DESKTOP-I36RVTN MINGW64 /d/lollilol/Desktop/discord-netflix (master)
$ npm run dist

> Netflix@2.0.0 dist D:\lollilol\Desktop\discord-netflix
> build

  • electron-builder version=19.56.2
  • loaded configuration file=package.json ("build" field)
Error: Unresolved node modules: register-scheme, electron-widevinecdm
    at D:\lollilol\Desktop\discord-netflix\node_modules\electron-builder-lib\src\util\packageDependencies.ts:109:19
From previous event:
    at Collector.resolveUnresolvedHoisted (D:\lollilol\Desktop\discord-netflix\node_modules\electron-builder-lib\out\util\packageDependencies.js:206:11)
    at D:\lollilol\Desktop\discord-netflix\node_modules\electron-builder-lib\src\util\packageDependencies.ts:85:18
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:632:19)
From previous event:
    at Collector.collect (D:\lollilol\Desktop\discord-netflix\node_modules\electron-builder-lib\out\util\packageDependencies.js:154:11)
    at computeDependencies (D:\lollilol\Desktop\discord-netflix\node_modules\electron-builder-lib\src\util\packageDependencies.ts:50:26)
    at D:\lollilol\Desktop\discord-netflix\node_modules\electron-builder-lib\src\util\packageDependencies.ts:45:28
    at Generator.next (<anonymous>)
From previous event:
    at getProductionDependencies (D:\lollilol\Desktop\discord-netflix\node_modules\electron-builder-lib\out\util\packageDependencies.js:29:21)
    at Lazy (D:\lollilol\Desktop\discord-netflix\node_modules\electron-builder-lib\src\util\packageDependencies.ts:39:25)
    at Lazy.get value [as value] (D:\lollilol\Desktop\discord-netflix\node_modules\lazy-val\src\main.ts:18:23)
    at D:\lollilol\Desktop\discord-netflix\node_modules\electron-builder-lib\src\util\yarn.ts:120:81
    at Generator.next (<anonymous>)
From previous event:
    at rebuild (D:\lollilol\Desktop\discord-netflix\node_modules\electron-builder-lib\out\util\yarn.js:93:22)
    at D:\lollilol\Desktop\discord-netflix\node_modules\electron-builder-lib\src\util\yarn.ts:20:11
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:632:19)
From previous event:
    at installOrRebuild (D:\lollilol\Desktop\discord-netflix\node_modules\electron-builder-lib\out\util\yarn.js:31:21)
    at D:\lollilol\Desktop\discord-netflix\node_modules\electron-builder-lib\src\packager.ts:442:7
    at Generator.next (<anonymous>)
From previous event:
    at Packager.installAppDependencies (D:\lollilol\Desktop\discord-netflix\node_modules\electron-builder-lib\out\packager.js:496:11)
    at D:\lollilol\Desktop\discord-netflix\node_modules\electron-builder-lib\src\packager.ts:356:20
    at Generator.next (<anonymous>)
From previous event:
    at Packager.doBuild (D:\lollilol\Desktop\discord-netflix\node_modules\electron-builder-lib\out\packager.js:432:11)
    at D:\lollilol\Desktop\discord-netflix\node_modules\electron-builder-lib\src\packager.ts:308:52
From previous event:
    at Packager._build (D:\lollilol\Desktop\discord-netflix\node_modules\electron-builder-lib\out\packager.js:376:11)
    at D:\lollilol\Desktop\discord-netflix\node_modules\electron-builder-lib\src\packager.ts:270:23
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (D:\lollilol\Desktop\discord-netflix\node_modules\electron-builder-lib\out\packager.js:332:11)
    at D:\lollilol\Desktop\discord-netflix\node_modules\electron-builder\src\builder.ts:310:40
    at Generator.next (<anonymous>)
From previous event:
    at _build (D:\lollilol\Desktop\discord-netflix\node_modules\electron-builder\out\builder.js:61:21)
    at build (D:\lollilol\Desktop\discord-netflix\node_modules\electron-builder\src\builder.ts:280:10)
    at then (D:\lollilol\Desktop\discord-netflix\node_modules\electron-builder\src\cli\cli.ts:48:33)
    at processImmediate (timers.js:632:19)
From previous event:
    at Object.args [as handler] (D:\lollilol\Desktop\discord-netflix\node_modules\electron-builder\src\cli\cli.ts:48:33)
    at Object.runCommand (D:\lollilol\Desktop\discord-netflix\node_modules\yargs\lib\command.js:235:44)
    at Object.parseArgs [as _parseArgs] (D:\lollilol\Desktop\discord-netflix\node_modules\yargs\yargs.js:1074:24)
    at Object.get [as argv] (D:\lollilol\Desktop\discord-netflix\node_modules\yargs\yargs.js:989:21)
    at Object.<anonymous> (D:\lollilol\Desktop\discord-netflix\node_modules\electron-builder\src\cli\cli.ts:42:15)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:760:12)
    at startup (internal/bootstrap/node.js:308:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:878:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Netflix@2.0.0 dist: `build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Netflix@2.0.0 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lollilol\AppData\Roaming\npm-cache\_logs\2018-11-20T15_54_32_771Z-debug.log

lollilol@DESKTOP-I36RVTN MINGW64 /d/lollilol/Desktop/discord-netflix (master)
$
```

**Comment by nirewen** [comment]
Yeah this electron-widevine error happens sometimes... The fix I found was by trying again until it doesn't throw this error...

**Comment by NovusTheory** [comment]
You need the register-scheme package added to run dist, or optionally set the env var to let electron builder fetch it for you

**Comment by lollilol** [comment]
so what do i have to type? :P

**Comment by nirewen** [comment]
This should be fixed as register-scheme is now a dependency of this project.
